# LOCAL ONLY - DO NOT COMMIT
apiVersion: v1
kind: Secret
metadata:
  name: advert-db-secret
  namespace: advert-back
type: Opaque
stringData:
  POSTGRES_DB: advertising_db
  POSTGRES_USER: advertising_user
  POSTGRES_PASSWORD: advertising_pass
